variables:
  CI_REGISTRY_USER: ase40
  CI_REGISTRY_PASSWORD: ASE123ase123

stages:
  - build
  - docker
  - deploy

build-job:
  image: maven:3.8.7-eclipse-temurin-17
  stage: build
  script:
  - cd microservices/
  - mvn clean install -B

docker-job:
  stage: docker
  image: maven:3.8.7-eclipse-temurin-17
  script:
    - cd microservices/
    - echo "Deploying to Docker hub... This will take some time."
    - mvn compile jib:build -Djib.to.auth.username=${CI_REGISTRY_USER} -Djib.to.auth.password=${CI_REGISTRY_PASSWORD}
    - echo "Deployment to Docker hub Done!"


deploy-job:
  stage: deploy
  script:
    - echo "Running linode trigger script..."
    - docker-compose up -d
    - echo "Done. Changes are live!"

