variables:
  CI_REGISTRY_USER: ase40
  CI_REGISTRY_PASSWORD: ASE123ase123


stages:
  - deploy


deploy-job:
  stage: deploy
  script:
    - echo "Running linode trigger script..."
    - apt-get update
    - apt-get install sshpass
    - sshpass -p "ASE123ase123" -o stricthostkeychecking=no ssh -tt root@139.144.181.63 "docker-compose down; docker-compose up -d"
    - echo "Done. Changes are live!"

