variables:
  CI_REGISTRY_USER: ase40
  CI_REGISTRY_PASSWORD: ASE123ase123

stages:
  - deploy


deploy-job:
  stage: deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PW
  script:
    - cd microservices/
    - echo "Running linode trigger script..."
    - docker compose up -d
    - echo "Done. Changes are live!"
