variables:
  CI_REGISTRY_USER: ase40
  CI_REGISTRY_PASSWORD: ASE123ase123

stages:
  - deploy


deploy-job:
  stage: deploy
  image: docker:20.10.16
  script:
    - cd microservices/
    - echo "Running linode trigger script..."
    - docker compose up -d
    - echo "Done. Changes are live!"
