---
version: "3"
services:
  ## Frontned
  ui-service:
    container_name: ui-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_URL=localhost:8080
