---
version: "3"
services:
  ## Eureka Server
  discovery-server:
    image: ase40/discovery-server:latest
    container_name: discovery-server
    pull_policy: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  ## Api gateway
  api-gateway:
    image: ase40/api-gateway:latest
    container_name: api-gateway
    pull_policy: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server

  ## Delivery Service
  delivery-service:
    image: ase40/delivery-service:latest
    container_name: delivery-service
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway

  ## Delivery Service!
  authentication-service:
    image: ase40/authentication-service:latest
    container_name: authentication-service
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway

  ## Frontned
  ui-service:
    image: ase40/ui-service:latest
    container_name: ui-service
    depends_on:
      - api-gateway
    pull_policy: always
    ports:
      - 2001:80
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_URL=139.162.132.244:8080
