---
version: "3"
services:
  discovery-server:
    container_name: discovery-server
    build:
      context: ./microservices/discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    container_name: api-gateway
    build:
      context: ./microservices/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server

  ## Delivery Service
  delivery-service:
    container_name: delivery-service
    build:
      context: ./microservices/delivery-service
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DELIVERY_MONGO_URL=${DELIVERY_MONGO_URL}
    depends_on:
      - discovery-server
      - api-gateway

  ## Delivery Service!
  authentication-service:
    container_name: authentication-service
    build:
      context: ./microservices/authentication-service
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH_MONGO_DB=${AUTH_MONGO_DB}
    depends_on:
      - discovery-server
      - api-gateway
  ## Frontned
  ui-service:
    container_name: ui-service
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_URL=localhost:8080
