eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
          - id: authentication-service
            uri: lb://authentication-service
            predicates:
              - Path=/api/auth/**
          - id: delivery-service
            uri: lb://delivery-service
            predicates:
              - Path=/api/delivery/**